# Generated by Django 5.2.10 on 2026-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='education', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
