# Generated by Django 5.2.10 on 2026-02-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_skill_category_skill_latitude_skill_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='members.member')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='members.member')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.skill')),
            ],
        ),
    ]
