# Generated by Django 5.2.10 on 2026-02-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_skillrequest_note_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesession',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.skillrequest'),
        ),
    ]
